# Rust代码格式化配置

# 基础配置
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# 导入配置
reorder_imports = true

# 函数配置
fn_params_layout = "Tall"

# 注释配置

# 字符串配置

# 其他配置
remove_nested_parens = true
use_small_heuristics = "Default"
newline_style = "Auto"

# 格式化宏

# 控制流

# 结构体和枚举

# 链式调用
chain_width = 60
single_line_if_else_max_width = 50
