# Rust代码格式化配置

# 基础配置
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# 导入配置
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"

# 函数配置
fn_args_layout = "Tall"
brace_style = "SameLineWhere"

# 注释配置
comment_width = 80
wrap_comments = true
normalize_comments = true

# 字符串配置
string_lit_normalize_whitespace = false

# 其他配置
remove_nested_parens = true
use_small_heuristics = "Default"
newline_style = "Auto"

# 格式化宏
format_macro_matchers = true
format_macro_bodies = true

# 控制流
control_brace_style = "AlwaysSameLine"
indent_style = "Block"

# 结构体和枚举
struct_lit_single_line = true
enum_discrim_align_threshold = 0

# 链式调用
chain_width = 60
single_line_if_else_max_width = 50
