[global]
# 飞书webhook URL
default_feishu_webhook_url = "https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# 全局检测间隔，单位秒（默认60）
check_interval_seconds = 60

# 日志级别（可选，默认"info"）
log_level = "info"

# 请求超时时间，单位秒（默认10）
request_timeout_seconds = 10

# 最大并发检测数（默认50）
max_concurrent_checks = 50

[[services]]
name = "示例API服务"
url = "https://api.example.com/health"
method = "GET"
expected_status_codes = [200, 201]
failure_threshold = 2
enabled = true
description = "示例API健康检测"
alert_cooldown_secs = 60               # 可选，告警最小间隔（秒），时间退避，默认60

[[services]]
name = "示例Web服务"
url = "https://www.example.com"
method = "GET"
expected_status_codes = [200]
failure_threshold = 1
enabled = true
description = "示例Web服务健康检测"
