name: Manual Build

# 手动触发构建工作流
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "构建类型"
        required: true
        default: "debug"
        type: choice
        options:
          - debug
          - release
      run_tests:
        description: "是否运行测试"
        required: true
        default: true
        type: boolean

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  manual-build:
    name: Manual Build for Ubuntu Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check code formatting
        run: cargo fmt -- --check

      - name: Run Clippy lints
        run: cargo clippy -- -W clippy::all -A clippy::too_many_arguments -A clippy::new_without_default -A clippy::field_reassign_with_default -A clippy::derivable_impls -A clippy::large_enum_variant -A clippy::for_kv_map -A clippy::unnecessary_map_or -A clippy::needless_borrows_for_generic_args -A clippy::redundant_closure -A clippy::clone_on_copy -A clippy::unnecessary_lazy_evaluations -A dead_code -A unused_variables

      - name: Run tests
        if: ${{ inputs.run_tests }}
        run: cargo test --verbose

      - name: Build debug binary
        if: ${{ inputs.build_type == 'debug' }}
        run: cargo build --verbose

      - name: Build release binary
        if: ${{ inputs.build_type == 'release' }}
        run: cargo build --release --verbose

      - name: Create build info
        run: |
          echo "Manual build completed at: $(date)" > manual-build-info.txt
          echo "Build type: ${{ inputs.build_type }}" >> manual-build-info.txt
          echo "Tests run: ${{ inputs.run_tests }}" >> manual-build-info.txt
          echo "Commit: ${{ github.sha }}" >> manual-build-info.txt
          echo "Branch: ${{ github.ref_name }}" >> manual-build-info.txt

      - name: Upload debug build artifacts
        if: ${{ inputs.build_type == 'debug' }}
        uses: actions/upload-artifact@v4
        with:
          name: service-vitals-debug-${{ github.sha }}
          path: |
            target/debug/service-vitals
            manual-build-info.txt
          retention-days: 7

      - name: Upload release build artifacts
        if: ${{ inputs.build_type == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: service-vitals-release-${{ github.sha }}
          path: |
            target/release/service-vitals
            manual-build-info.txt
          retention-days: 7
